apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetyhome
  labels:
    app: tweetyhome
  namespace: tweety-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetyhome
  template:
    metadata:
      labels:
        app: tweetyhome
    spec:
      containers:
        - name: tweetyhome
          image: karthiv89/tweetyhome:1.0
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tweetyhome
  namespace: tweety-microservice
spec:
  selector:
    app: tweetyhome
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
